language: go
sudo: false

go:
  - "1.9"
  - "1.10"
  - master
  - tip
before_install:
  - go get github.com/mattn/goveralls


install:
  - go get -v github.com/mitchellh/gox
  - go get -t -v ./...


jobs:
  include:
    - stage: Geofabrik
      script: make geofabrik
    - stage: OSMfr
      script: make osmfr
    - stage: GisLab
      script: make gislab
    - stage: Readme
      script: make readme
    - stage: test
      script:
        - go test -bench=. -benchmem -v ./...
        - $GOPATH/bin/goveralls -service=travis-ci 
    - stage: build
      script: make
    - stage: deploy
      script: skip
      go: "1.10" 
      deploy:
        provider: releases
        api_key:
          secure: "o+lsHtm1FV0Hu/FHOyujZE11pTJuexUwWQtbiYr21Z4+BEcDzVN+Pxr2s1JnmNKcl7wqNBVSyNAnXUpqUWcgwi9liM9dOn+DcHUAT4eMM/zTm9vgf1qjxfoDJK3suXLQlzRNGkygz6PFGZvICjSmJTDsGTNpEIezFdXupOvZgnc5CT7qp+xBB95tQlWfaRVeCkSKqRyOK09J+scliwJR6SZlGqBUSDkb9RPMxpZ2wjNYf8fWQFHtzBcutT9gFJZLE2WPei6or6jOm7i6Haaa7Pg4Lhrlge7N1fq6FsQbcHqLX3F349voN5Nt+TtxY3sIeACNHqNkEuxkQnjAkTKoF+DTODXnwOjp6Mp1xb4LK+ejfYUppF6384sFDmKIc7xNJU1Mmwp+Bqw1q3WNyYqAbwLTC/UIlADIVglOH9r8bLJGikRPJPR3QnEznIL06l5lM34wNicvhqSKSIf06kxAXwAK7QD6prBPuTmlCZFNDASDw7E/IjUd3tXTgYvj8Fb8pMa4jsb7Bafgbo2sliicFuC+ua7CWvTWjlsMSJPLkdbEJku1VSdTTTV/rK8sqRbgc/Q/8BOQm/6ZCGntWtHacsefopaMuJR7hhMUaviNZOsjUunn+fkTNWByLX2nHHJAuyNbAXgpxwIkGGZONvfNxgi8Dw2Oz5sM6EUcKxSxTBM="
        file:
          - "download-geofabrik_darwin_386.zip"
          - "download-geofabrik_darwin_amd64.zip"
          - "download-geofabrik_freebsd_386.zip"
          - "download-geofabrik_freebsd_amd64.zip"
          - "download-geofabrik_freebsd_arm.zip"
          - "download-geofabrik_linux_386.zip"
          - "download-geofabrik_linux_amd64.zip"
          - "download-geofabrik_linux_arm.zip"
          - "download-geofabrik_netbsd_386.zip"
          - "download-geofabrik_netbsd_amd64.zip"
          - "download-geofabrik_netbsd_arm.zip"
          - "download-geofabrik_openbsd_386.zip"
          - "download-geofabrik_openbsd_amd64.zip"
          - "download-geofabrik_windows_386.zip"
          - "download-geofabrik_windows_amd64.zip"

        skip_cleanup: true
        on:
          tags: true

stages: 
  - Geofabrik
  - OSMfr
  - GisLab
  - Readme
  - test
  - build
  - deploy